package model;
// Generated Feb 17, 2019 12:11:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,catalog="emp3"
)
public class Department  implements java.io.Serializable {


     private Long id;
     private String departmentName;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

	
    public Department(String departmentName) {
        this.departmentName = departmentName;
    }
    public Department(String departmentName,  Set<Employee> employees) {
       this.departmentName = departmentName;
       this.employees = employees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="departmentName", nullable=false)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }



@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }


}


