package model;
// Generated Feb 17, 2019 12:11:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="emp3"
)
public class User  implements java.io.Serializable {


     private Long id;
     private String userId;
     private String userName;
     private String psssword;
     private String userRole;

    public User() {
    }

    public User(String userId, String userName, String psssword, String userRole) {
       this.userId = userId;
       this.userName = userName;
       this.psssword = psssword;
       this.userRole = userRole;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="userName", nullable=false)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="psssword", nullable=false)
    public String getPsssword() {
        return this.psssword;
    }
    
    public void setPsssword(String psssword) {
        this.psssword = psssword;
    }

    
    @Column(name="userRole", nullable=false)
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }




}


